dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - requests
    - fake_useragent
    - scrapy
    - cookies
    - bs4
    - pandas
    - pymysql
