dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - requests
    - fake-useragent
    - scrapy
    - url
    - tornado
    - pyspider
